services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123

  # adminer service to manage the database
  adminer:
    image: adminer:latest
    ports:
      - '1010:8080'
    restart: always
    depends_on:
      - db