services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123

  # adminer service to manage the database
  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db

    #keycloak service for identity and access management
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - '9090:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file

volumes:
  keycloak-data:
    driver: local